version: '3'

networks:
  test-bridge:
    driver: bridge

services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - test-bridge
    depends_on:
      - db
 
  db: 
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=test_task
      - MYSQL_USER=test
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    networks:
      - test-bridge
